### ISSUE TITLE
Code execute - Not working

### ISSUE THREAD

**Issue by Audngapala** [Dev-Environments/VScode#22]
The Run/Terminal is not working, I hope it will be fixed soon. so that your "VScode for mobile" will be better, act on it immediately. 

Pst: "I can't send a picture because it's too big mb"

**Comment by Dev-Environments** [comment]
Please explain what happens when you open a Terminal. Clear your Point. So, we do work on fixing this issue. Thanks

**Comment by Audngapala** [comment]
Not work to Run my work code

**Comment by Dev-Environments** [comment]
> Thanks for clarifying that you're unable to run code from the Terminal.   Let me explain what's happening and how to fix it. 
>
> ⚠️ Android has security rules that prevent code execution from the VScode folder because it's in internal storage. This is to protect your device and data. 
>
>  Here's where you *can* run code:
>
> 1️⃣ **Git Folder:** This is the preferred spot for code storage and execution. 
>
> To get things working:
>
> 1. **Move Your Code:** If your code is in the VScode folder, please move it to either the Git folder.
> 2. **Set Working Directory:** In the Terminal, use the `cd` command to navigate to the correct directory before running your code. Example: `cd /root/Git` to go to the Git folder. 
>
> **File System Structure:**
>
> - VScode folder: `emulated/VScode` (not for code execution) 
> - Git folder: App Data directory (use for code execution)  ✅
>
> We're always working to improve VScode for mobile, and we appreciate your feedback!  If you still have trouble after following these steps, please share more details about any error messages or weird behaviors you're seeing. 
>
> Thanks for your patience and understanding!

**Comment by Dev-Environments** [comment]
Thanks for clarifying that you're unable to run code from the Terminal.   Let me explain what's happening and how to fix it. 

⚠️ Android has security rules that prevent code execution from the VScode folder because it's in internal storage. This is to protect your device and data. 

 Here's where you *can* run code:

1️⃣ **Git Folder:** This is the preferred spot for code storage and execution. 

To get things working:

1. **Move Your Code:** If your code is in the VScode folder, please move it to either the Git folder.
2. **Set Working Directory:** In the Terminal, use the `cd` command to navigate to the correct directory before running your code. Example: `cd /root/Git` to go to the Git folder. 

**File System Structure:**

- VScode folder: `emulated/VScode` (not for code execution) 
- Git folder: App Data directory (use for code execution)  ✅

We're always working to improve VScode for mobile, and we appreciate your feedback!  If you still have trouble after following these steps, please share more details about any error messages or weird behaviors you're seeing. 

Thanks for your patience and understanding!
