### ISSUE TITLE
Isn't Visual Studio Code a Microsoft Trade Mark? 

### ISSUE THREAD

**Issue by Ordiel** [Dev-Environments/VScode#38]
I think this project falls into the not authorized Comercial use of a Microsoft Trade Mark product

https://www.microsoft.com/en-us/legal/terms-of-use

> Unless otherwise specified, the Services are for your personal and non-commercial use. You may not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information, software, products or services obtained from the Services.

This is not only using their logo but it's also charging (no less than $6.99) for it

**Comment by kpriyanshu2003** [comment]
VS Code is open source project. Just like all other projects on GitHub. It is protected by MIT Licence, which mean anyone is free for personal as well as commercial use. Except for liability and warranty. So he ( the developer ) is free to create anything out of it. 
You may want to check this out. [License for VS Code](https://github.com/microsoft/vscode/blob/main/LICENSE.txt)

The link you've provided is applicable for all Microsoft services and softwares which are closed source, such as Windows and MS Office.

**Comment by Ordiel** [comment]
The code is open source, yet Visual Studio Code is apparently a trade mark, partially that is the reason for VSCodium to exist

https://vscodium.com/

![image](https://github.com/Dev-Environments/VScode/assets/9622612/c07288b3-b977-433a-afd7-fcd93336e51e)

You might be interested on reviewing the [following answer](https://github.com/microsoft/vscode/issues/60#issuecomment-161792005) and as you can see on the [Visual Studio Code FAQ](https://code.visualstudio.com/docs/supporting/faq), it is subject to the terms of used linked above

![image](https://github.com/Dev-Environments/VScode/assets/9622612/bf548dd0-5152-49e4-9c33-9402ff466b92)

FYI: The reason I ask is 'cuz I wouldn't like to buy the product just to see it removed from the store and me losing the app

**Comment by kpriyanshu2003** [comment]
I totally get your point. The thing is VS Code as OSS is under the MIT licence. But, the distribution (installer) which is available to download for a user comes under Microsoft licence. 
It basically means, VS Code on GitHub is free for personal and commercial use. But, the distribution provided by Microsoft is not. 
And, if you are worried about if this app will be gone from play store or not. I can partially guarantee you that it will not. 
@Dev-Environments shall have final say regarding this.

**Comment by Mrxx99** [comment]
> And, if you are worried about if this app will be gone from play store or not. I can partially guarantee you that it will not. 

It is gone now.
https://play.google.com/store/apps/details?id=dev.environment.VScode_Paid

**Comment by Dev-Environments** [comment]
> > And, if you are worried about if this app will be gone from play store or not. I can partially guarantee you that it will not.
> 
> It is gone now. https://play.google.com/store/apps/details?id=dev.environment.VScode_Paid

Yes, it is Gone Because of Icon is Trademark According to "Matthew Dean" in the below Email which i Received from Google Play Console Team.

Must Read this: [Gmail - Action Required_ Your app is not compliant with Google Play Policies (VScode for Android).pdf](https://github.com/Dev-Environments/VScode/files/11929787/Gmail.-.Action.Required_.Your.app.is.not.compliant.with.Google.Play.Policies.VScode.for.Android.pdf)

I Searched About these Trademark: VISUAL STUDIO DESIGN 201, us, 4314894 & VS CODE, US, 7069280
1. I asked to **Bard** that: [how can i find this trademark where is it registered _Trademarks_ VISUAL STUDIO DESIGN 201, us, 4314894; VS CODE, US, 7069280_ - Google Docs.pdf](https://github.com/Dev-Environments/VScode/files/11929976/how.can.i.find.this.trademark.where.is.it.registered._Trademarks_.VISUAL.STUDIO.DESIGN.201.us.4314894.VS.CODE.US.7069280_.-.Google.Docs.pdf)
2. According to **[Bard Response](https://github.com/Dev-Environments/VScode/files/11929976/how.can.i.find.this.trademark.where.is.it.registered._Trademarks_.VISUAL.STUDIO.DESIGN.201.us.4314894.VS.CODE.US.7069280_.-.Google.Docs.pdf)** I searched on [this](https://tsdr.USPTO.gov) web about these two Trademarks Registration No# 4314894 & 7069280 and then i found that [this](https://tsdr.uspto.gov/#caseNumber=4314894&caseSearchType=US_APPLICATION&caseType=SERIAL_NO&searchType=statusSearch) Trademark Icon is not our App icon. So, we are not using Trademark Infringement in Our App VScode for Android.

**Now, What you say & Must Read All Attachments**

**Comment by Mrxx99** [comment]
https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks

Just change the icon and the name. I really wondered how this was allowed when I saw the app, turns out it wasn't.

**Comment by Ordiel** [comment]
I guess its a good thing I didn't paid for it...

**Comment by Dev-Environments** [comment]
App icon and other Publishing issues are fixed Now

**Comment by Dev-Environments** [comment]
App is back NOW checkout the link https://play.google.com/store/apps/details?id=dev.environment.VScode_PaidR1
We are providing a way to get this app for free if you already paid for it. then must check this https://vscodeform.dev-environments.com
And Thanks for your Patience.
